import { Product } from '../types';

export const seedProducts: Product[] = [
  {
    id: '1',
    name: 'Oud Al Shams',
    brand: 'Arabian Essence',
    price: 12500,
    originalPrice: 15000,
    description: 'A captivating blend of rare Agarwood and amber that commands respect.',
    longDescription: 'Oud Al Shams is an ode to the ancient trade routes of Arabia. Opening with a burst of smoky Agarwood, it settles into a warm heart of precious amber and rose, leaving a trail of rich sandalwood and musk that lingers for hours. Crafted for the modern man who honours tradition.',
    category: 'oud',
    size: ['50ml', '100ml'],
    images: [
      'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=600&q=80',
      'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80',
    ],
    topNotes: ['Agarwood', 'Bergamot', 'Black Pepper'],
    heartNotes: ['Amber', 'Rose', 'Saffron'],
    baseNotes: ['Sandalwood', 'Musk', 'Patchouli'],
    inStock: true,
    featured: true,
    bestseller: true,
    stockQuantity: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Noir Majesty',
    brand: 'Desert King',
    price: 9800,
    description: 'Bold, dark, commanding — the scent of power.',
    longDescription: 'Noir Majesty opens with an explosive burst of cardamom and leather, evolving into a deeply resonant heart of dark woods and tobacco. The base is anchored by vetiver and aged oud, creating a presence that is impossible to ignore. A fragrance for those who lead.',
    category: 'woody',
    size: ['50ml', '100ml', '150ml'],
    images: [
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80',
      'https://images.unsplash.com/photo-1575728252059-db65ded67e33?w=600&q=80',
    ],
    topNotes: ['Cardamom', 'Leather', 'Juniper'],
    heartNotes: ['Dark Woods', 'Tobacco', 'Incense'],
    baseNotes: ['Vetiver', 'Aged Oud', 'Ambergris'],
    inStock: true,
    featured: true,
    bestseller: false,
    stockQuantity: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Mukhallat Al Layl',
    brand: 'Oud Noir',
    price: 16500,
    description: 'A symphony of rare musks and sacred woods. Night in a bottle.',
    longDescription: 'Mukhallat Al Layl — meaning "Blend of the Night" — is a masterwork of Arabic perfumery. This complex composition layers white musk over a heart of mystical frankincense and East Indian sandalwood. Reserved for those who appreciate the extraordinary.',
    category: 'oriental',
    size: ['50ml', '100ml'],
    images: [
      'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&q=80',
      'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80',
    ],
    topNotes: ['White Musk', 'Violet Leaf', 'Citrus'],
    heartNotes: ['Frankincense', 'Sandalwood', 'Neroli'],
    baseNotes: ['Ambergris', 'Oakmoss', 'Benzoin'],
    inStock: true,
    featured: true,
    bestseller: true,
    stockQuantity: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Amber Royale',
    brand: 'Arabian Essence',
    price: 8900,
    description: 'Warm, enveloping amber that wraps you in golden warmth.',
    longDescription: 'Amber Royale is a rich, warm fragrance built around the finest labdanum absolute and golden amber. Sweet vanilla and benzoin add a gourmand quality, while oakmoss and cistus root the composition in the earth. Deeply comforting and undeniably masculine.',
    category: 'oriental',
    size: ['100ml'],
    images: [
      'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&q=80',
    ],
    topNotes: ['Bergamot', 'Pink Pepper', 'Grapefruit'],
    heartNotes: ['Amber', 'Labdanum', 'Jasmine'],
    baseNotes: ['Vanilla', 'Benzoin', 'Oakmoss'],
    inStock: true,
    featured: false,
    bestseller: false,
    stockQuantity: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Al Qudra',
    brand: 'Desert King',
    price: 11200,
    description: 'The essence of strength. Pure Oud elevated by rare spices.',
    longDescription: 'Al Qudra — meaning "The Power" — is an uncompromising oud fragrance for men who demand authenticity. Hind Oud is blended with rich saffron and a cumin accord, evoking the ancient spice markets of the Gulf. A classic reinterpreted with modern precision.',
    category: 'oud',
    size: ['50ml', '100ml'],
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
    ],
    topNotes: ['Saffron', 'Cumin', 'Lemon'],
    heartNotes: ['Hind Oud', 'Rose', 'Geranium'],
    baseNotes: ['Sandalwood', 'Musk', 'Labdanum'],
    inStock: true,
    featured: false,
    bestseller: true,
    stockQuantity: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Cedar & Smoke',
    brand: 'Oud Noir',
    price: 7500,
    description: 'Clean cedar smoke over a bed of warm grey musk.',
    longDescription: 'Cedar & Smoke is a study in contrasts — fresh and smouldering, clean and deep. Atlas cedarwood is gently kissed by birch tar smoke, softened by a generous grey musk base. The result is modern, wearable, and utterly compelling. For the discerning man.',
    category: 'woody',
    size: ['50ml', '100ml', '150ml'],
    images: [
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&q=80',
    ],
    topNotes: ['Atlas Cedar', 'Juniper Berry', 'Galbanum'],
    heartNotes: ['Birch Tar', 'Vetiver', 'Guaiac Wood'],
    baseNotes: ['Grey Musk', 'Iso E Super', 'Ambroxan'],
    inStock: true,
    featured: false,
    bestseller: false,
    stockQuantity: 50,
    createdAt: new Date().toISOString(),
  },
];
